config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  devise_for :users 
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do #memberによりidの識別がされるようになる（:idと同じ）
      get :followings, :followers
    end
    get :search, on: :collection #urlにidをつけない
  end
  resources :relationships, only: [:create, :destroy]

  #dm機能
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    get :search, on: :collection #urlにidをつけない
    resources :tags, only: [:show]
  end

  #通知機能
  resources :notifications, only: [:index, :destroy]
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    #通知機能追加
    @post = Post.find(params[:post_id])  #どの投稿にいいねしたか取得
    @post.create_notification_like!(current_user)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.alread_liked?(post) %>
  <%= link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true, class: 'unlike_btn' do %>
    <span class="likes-heart"><i class="fas fa-heart"></i></span>
    <span class="likes-count"><%= post.likes.count %></span>
  <% end %>
<% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true, class: 'like_btn'  do %>
    <span class="likes-heart"><i class="far fa-heart"></i></span>
    <span class="likes-count"><%= post.likes.count %></span>
    <% end %>
<% end %>
 

app/views/likes/create.js.erb
$(".like_btn").html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('.unlike_btn').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");