config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  devise_for :users 
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do #memberによりidの識別がされるようになる（:idと同じ）
      get :followings, :followers
    end
    get :search, on: :collection #urlにidをつけない
  end
  resources :relationships, only: [:create, :destroy]

  #dm機能
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    get :search, on: :collection #urlにidをつけない
    resources :tags, only: [:show]
  end

  #通知機能
  resources :notifications, only: [:index, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: {maximum: 18}       
  VALID_SYUDENT_ID_REGEX = /\A[A-Z0-9]+\z/i
  validates :student_id, presence: true, uniqueness: { case_sensitive: false }, length: {in: 7..8}, format: { with: VALID_SYUDENT_ID_REGEX,
    message: "は半角7~8文字で英大文字と数字で入力して下さい"}   
  validates :email,  uniqueness: {case_sensitive: false, message: "は既に使用されています"}     

  has_one_attached :user_photo
  attachment :profile_image   
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :post
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  #フォロー機能
  has_many :following_relationships,foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :followings, through: :following_relationships #架空のfollowingsモデルにアクセスしてフォローしているユーザーのidを取得できるようになる（relationshipsテーブルを中間テーブルとして使っている）
  has_many :follower_relationships,foreign_key: "following_id",class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships #フォローされているユーザーのidを取得できるようになる

  #DM機能
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries  #entriesテーブルを経由してroomの情報を取得するため

  #通知機能（notificationsテーブルに関連づけしている）
  has_many :active_notifications, foreign_key:"visitor_id", class_name: "Notification", dependent: :destroy #通知をした側
  has_many :passive_notifications, foreign_key:"visited_id", class_name: "Notification", dependent: :destroy #通知をされた側

  #閲覧履歴
  has_many :browsing_histories, dependent: :destroy

  
  def posts
    return Post.where(user_id: self.id)
  end

  # ユーザーがどの投稿にいいねしているか取得するため
  def alread_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  #フォロー機能
  #すでにフォロー済みであればture返す
  def following?(other_user)
    self.followings.include?(other_user)
  end

  #ユーザーをフォローする(selfにはuserのインスタンスが入る)
  def follow(other_user)
    self.following_relationships.create(following_id: other_user.id)
  end

  #ユーザーのフォローを解除する
  def unfollow(other_user)
    self.following_relationships.find_by(following_id: other_user.id).destroy
  end

  #通知機能
  def create_notification_follow!(current_user)
    #すでに通知が作成されているか確認
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  #検索機能
  def self.search(search)
    if search
      User.where('username LIKE ? OR student_id LIKE ?', "%#{search}%", "%#{search}%")
    else
      User.all
    end
  end

  #ゲストログイン
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.username = "ゲスト"
      user.student_id = "11TT111"
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest 
    user = User.guest
    sign_in user 
    redirect_to root_path, notice: 'ゲストとしてログインしました' 
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update, :followings, :followers ]
  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def show
    if user_signed_in? #ログインしているかどうか
      @currentUserEntry = Entry.where(user_id: current_user.id) #既にルームに参加しているかどうか確認するためentriesテーブルからuser_idがログインしているユーザーのidと一致するものを全て取得している
      @userEntry = Entry.where(user_id: @user.id) #ユーザー詳細のユーザーが既にルームに参加している確認（上と同じ）
      unless @user.id == current_user.id #ユーザー詳細のページのユーザーがログインしているユーザーでないことを確認
        @currentUserEntry.each do |cu| #上で取得したものを一つずつ取り出しcuに格納
          @userEntry.each do |u|  #上と同じ
            if cu.room_id == u.room_id #取り出したもののroom_idが同じであるか確認（既に部屋に入っているか）
              @haveRoom = true  #入っている場合 trueを@haveRoomに格納（既にルームが存在するという意味）
              @roomId = cu.room_id  #
            end
          end
        end
        unless @haveRoom  #ルームに入っていない場合 
          @room = Room.new #roomを新しく作る
          @entry = Entry.new #@roomと@entryをformで送るため
        end
      end
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  #フォロー機能
  def followings
    @users = @user.followings #@userにはどのユーザーであるかの情報が格納されていてuserモデルで定義したfollowingsでフォローした人を取得している
    render 'show_followings'
  end

  def followers
    @users = @user.followers #上の逆フォロワーバージョン
    render 'show_followers'
  end

  def search 
    @users = User.search(params[:search])
  end


  private 
  def user_params
    params.require(:user).permit(:username, :student_id, :email, :password, :user_photo, :profile)
  end

  def set_user
    @user =User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_contact.html.erb
<% if user_signed_in? %>
  <% unless @user.id == current_user.id %>
    <% if @haveRoom == true %>
      <%= link_to 'DMする', room_path(@roomId), class: 'already-dm-btn' %>
      <% else %>
        <%= form_with(model:@room, local: true) do |f|%> <%# roomコントローラーのcreateアクションを呼び出している%>
          <%= fields_for @entry do |e| %>  <%# form_with内で異なるモデルを編集することができるようになる %>
            <%= e.hidden_field :user_id, value: @user.id %>  <%# entriesテーブルにuser_idを保存するために送っている%>
          <% end %>
          <%= f.submit 'DMを始める', class: 'start-dm-btn' %>
        <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_follow.html.erb
<%#modelにはインスタンスが必要なので空のrelationshipインスタンスを作成している%>
<%= form_with(model: current_user.following_relationships.build ) do |f|%> 
  <%= f.hidden_field :following_id, value: @user.id %> <%#見えないように誰がフォローしたかの情報（following_id）を送っている%>
  <%= f.submit "フォローする", class: "follow-btn" %>
<% end %>

app/views/users/_unfollow.html.erb
<%#どのユーザーのフォローを外すのかを取得してrelationshipコントローラーのでdestroyアクションを呼んでいる %>
<%= form_with(model: current_user.following_relationships.find_by(following_id: @user.id),method: :delete) do |f| %>
  <%= f.hidden_field :following_id %>  
  <%= f.submit "フォロー中", class: "unfollow-btn" %>
<% end %>

app/views/users/_user_all.html.erb
    <div class="user-index-content">
        <div class="user-index-info">
          <table class="user-index-table">
            <thead>
              <tr>
                <th>プロフィール画像</th>
                <th>ユーザーネーム</th>
                <th>学籍番号</th>
                <th>プロフィール</th>
                <th>詳細</th>
              </tr>
            </thead>
          <% @users.each do |user|%>
            <tbody>
              <tr>
                <td>
                  <% if user.user_photo.attached? %>
                    <%= image_tag user.user_photo, class: 'no-image' %>
                  <% else %>
                    <%= image_tag 'no-image.png', class: 'no-image' %>
                  <% end %>
                </td>
                <td><%= user.username %></td>
                <td><%= user.student_id %></td>
                <td><%= simple_format(user.profile) %></td>
                <td><%= link_to '詳細', user_path(user.id), class: 'user-index-btn' %></td>
              </tr>
            </tbody>
          <% end %>  
          </table>
        </div>
    </div>

app/views/users/index.html.erb
<div class="user-index all-wrapper">
  <div class="user-index-container all-container">

   <div class="user-index-title">
        <h2>ユーザ一覧</h2>
    </div>

    <div class="search-form">
      <%= form_with url: search_users_path, method: :get, local: true do |f| %> <%# データベースに保存しない %>
        <%= f.text_field :search, placeholder: 'ユーザを検索する', class: 'seach-text-field' %>
        <%= f.submit '検索', class: 'seach-submit' %>
      <% end  %>
    </div>

    <%= render partial: 'user_all'%>
    
  </div>

  <div class="pagination-container">
    <%= paginate @users %>
  </div>

</div>

app/views/users/search.html.erb
<div class="user-index all-wrapper">
  <div class="user-index-container all-container">
     <%= link_to '前のページに戻る>>', :back, class: 'back-btn' %>
    <div class="user-index-title">
        <h2>検索結果<%= @users.count %>件</h2>
      </div>

      <%= render partial: 'user_all'%>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show all-wrapper">
  <div class="user-show-container all-container">
    <div class="user-show-title">
      <h2>ユーザ情報</h2>
    </div>  
    <div class="follow-dm-flex">

      <div class="to-chat-room">
        <% if @user == current_user %>
          <%= link_to 'DM一覧へ', rooms_path, class: 'all-dm' %>
        <% else %>
          <%= render 'contact'%>
        <% end %>
      </div>

      <div class="follow_form">
        <% if @user != current_user %>
          <%#ログイン中のユーザーが既にfollowしていたらunfollowにしていなければfollowするにする %>
          <% if current_user.following?(@user) %> 
            <%= render 'unfollow' %>
          <% else %>
            <%= render 'follow' %>
          <% end %>
        <% end %>
      </div>
      
    </div>  

    
    <div class="user-show-content">
      <div class="user-show-image">
        <% if @user.user_photo.attached? %>
          <%= image_tag @user.user_photo, class: 'no-image' %>
        <% else %>
          <%= image_tag 'no-image.png', class: 'no-image' %>
        <% end %>
      </div>
      <div class="user-show-username">
        <%= @user.student_id %>
        <%= @user.username %>
      </div>

      <div class="user-show-profile">
        <%= simple_format(@user.profile) %>
      </div>

      <%= link_to "フォロー#{@user.followings.count}", followings_user_path(@user), class: "relationship-btn" %>

      <%= link_to "フォロワー#{@user.followers.count}", followers_user_path(@user), class: "relationship-btn" %>

      <% if @user.id == current_user.id %>
        <div class="loginuser-only">
          <%= link_to '編集',edit_user_registration_path, class: 'loginuser-only-btn' %>
        </div>
      <% end %>
    
    </div>

    <%# 投稿一覧、いいね一覧、コメント一覧 %>
    <div class="tabmenu-btns">
      <p class="tabmenu-btn is-active-tab" data-id="tabmenu-post-all">投稿<span><%= @user.posts.count %></span></p>
      <p class="tabmenu-btn" data-id="tabmenu-like-all">いいね<span><%= @user.likes.count %></span></p>
      <p class="tabmenu-btn" data-id="tabmenu-comment-all">コメント<span><%= @user.comments.count %></span></p>
    </div>

    <div class="tabmenu-content is-active-content" id="tabmenu-post-all">
      <% if @user.posts.present? %>
        <div class="tabmenu-container">
          <% @user.posts.each do |post| %>
            <div class="tabmenu-post-link">
              <%= link_to post_path(post), class: 'link_to_mypost' do %>
                <div class="tabmenu-post-content">

                  <div class="tabmenu-post-image">
                    <% if post.post_photo.attached? %>
                      <%= image_tag post.post_photo, class: 'tabmenu-post-img' %>
                    <% else %>
                      <%= image_tag 'nothing-image.png', class: 'tabmenu-post-img' %>
                    <% end %>
                  </div>

                  <div class="tabmenu-post-title">
                    <%= post.title %>
                  </div>

                </div>
              <% end %>
            </div> 
          <% end %>
        </div>
      <% else %>
        <div class="all-nothing">
          <p>投稿はありません</p>
        </div>
      <% end  %>
    </div>

    <%# いいね一覧 %>
    <div class="tabmenu-content" id="tabmenu-like-all">
      <% if @user.liked_posts.present? %>
        <div class="tabmenu-container">
          <% @user.liked_posts.each do |post| %>
            <div class="tabmenu-post-link">
              <%= link_to post_path(post) do %>
                <div class="tabmenu-post-content">

                  <div class="tabmenu-post-image">
                    <% if post.post_photo.attached? %>
                      <%= image_tag post.post_photo, class: 'tabmenu-post-img' %>
                    <% else %>
                      <%= image_tag 'nothing-image.png', class: 'tabmenu-post-img' %>
                    <% end %>
                  </div>

                  <div class="tabmenu-post-title">
                    <%= post.title %>
                  </div>

                </div>
              <% end %>
            </div> 
          <% end %>
        </div>
      <% else %>
        <div class="all-nothing">
          <p>いいねした投稿はありません</p>
        </div>
      <% end %>
    </div>


  <%# コメント一覧 %>
    <div class="tabmenu-content" id="tabmenu-comment-all">
      <% if @user.comments.present? %>
        <div class="tabmenu-container">
          <% @user.comments.reverse.each do |comment| %>
            <div class="tabmenu-comment-link">
              <%= link_to post_path(comment.post_id) do %>
                <div class="comment-all">

                  <div class="comment-user-images">
                    <% if @user.user_photo.attached? %>
                      <%= image_tag @user.user_photo, class: 'comment-user-img' %>
                    <% else %>
                      <%= image_tag 'no-image.png', class: 'comment-user-img' %>
                    <% end %>
                  </div>

                  <div class="comment-content comment-user-content">
                    <%= simple_format(comment.content ) %>
                  </div>
                
                </div>
                 <p class="comment-time"><%= comment.set_date%></p>
              <% end %>
            </div> 
          <% end %>
        </div>
      <% else %>
        <div class="all-nothing">
          <p>コメントした投稿はありません</p>
        </div>
      <% end %>
    </div>

  </div>
</div>

<%= javascript_pack_tag 'user/show' %>




  
  

app/views/users/show_followers.html.erb
<div class="user-index all-wrapper">
  <div class="user-index-container all-container">

   <div class="user-index-title">
        <h2><%= @user.username %>さんのフォロワー一覧</h2>
    </div>

    <%= render partial: 'user_all'%>
    
  </div>
</div>

app/views/users/show_followings.html.erb
<div class="user-index all-wrapper">
  <div class="user-index-container all-container">

   <div class="user-index-title">
        <h2><%= @user.username %>さんがフォローしているユーザー</h2>
    </div>

    <%= render partial: 'user_all'%>

  </div>
</div>