config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  devise_for :users 
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do #memberによりidの識別がされるようになる（:idと同じ）
      get :followings, :followers
    end
    get :search, on: :collection #urlにidをつけない
  end
  resources :relationships, only: [:create, :destroy]

  #dm機能
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    get :search, on: :collection #urlにidをつけない
    resources :tags, only: [:show]
  end

  #通知機能
  resources :notifications, only: [:index, :destroy]
  
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :likes, dependent: :destroy
  # 投稿が誰にいいねされているかを取得するため
  has_many :liked_users, through: :likes, source: :user
  has_one_attached :post_photo
  attachment :image 

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true, length: {in: 3..500}

  #通知機能
  has_many :notifications, dependent: :destroy

  #tag機能
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  #閲覧履歴
  has_many :browsing_histories, dependent: :destroy

  #いいねの通知機能のメソッド
  def create_notification_like!(current_user)
    #既にいいねしているかどうか確認（連打しても通知が何回も送られないように）
    #sqlインジェクションを防ぐため？（プレイスホルダー）を使っている（置き換え可能）
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
                                  current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )

      #自分の投稿に対するいいねは通知済みにしておくため
      if notification.visitor_id == notification.visited_id
         notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id) #この中じゃcomment_idを指定できないから引数を用いている
    #同じ投稿にコメントしているユーザーに通知を送る。（current_userと投稿ユーザーのぞく）
    #distinctで複数回コメントしているへとの通知の一回にしている
    temp_ids = Comment.where(post_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    #取得したユーザー達へ通知を作成。（user_idのみ繰り返し取得）
    temp_ids.each do |temp_id| #temp_idにはselectされた中のひとりひとりのユーザが入っている（ログイン中のユーザと投稿者以外）
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    #投稿者へ通知を作成
    save_notification_comment!(current_user, comment_id, user_id)
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
      notification = current_user.active_notifications.new(
        post_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end

  #投稿検索機能
  def self.post_search(search)
     #postsテーブルのtitleカラムからparams[:search] = 引数search（検索した内容）が入っている投稿を抽出している
    if search 
      Post.where('title LIKE ?', "%#{search}%")
    else 
      Post.all
    end
  end

  #tag機能
  def save_tag(sents_tag)
    unless self.tags.nil?
    current_tags = self.tags.pluck(:tag_name) 
    end
    old_tags = current_tags - sents_tag
    new_tags = sents_tag - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      posts_tag = Tag.find_or_create_by(tag_name: new_name)
      self.tags << posts_tag
    end
  end

  #ランキング機能
  def self.likes_ranking 
    Post.find(Like.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end
      
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy ]
  before_action :set_tag, only: [:index, :search,]
  before_action :set_ranking, only: [:index, :search,]
  before_action :set_history, only: [:index, :search,]
  def index
    @posts = Post.page(params[:page]).per(10)
    @current_time= Time.current
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @like = Like.new

    new_history = @post.browsing_histories.new
    new_history.user_id = current_user.id

    if current_user.browsing_histories.exists?(post_id: "#{params[:id]}")
      old_history = current_user.browsing_histories.find_by(post_id: "#{params[:id]}")
      old_history.destroy
    end

    unless new_history.user_id == @post.user_id
      new_history.save
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_list = params[:post][:tag_name].split(",")
    if @post.save
      #タグ機能
      @post.save_tag(tag_list)
      #ここまで

      flash[:success] = "新しく投稿しました"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @tag_list = @post.tags.pluck(:tag_name).join(",")
    if @post.user != current_user
      redirect_to posts_path, alert: '不正なアクセスです'
    end
  end

  def update 
    tag_list = params[:post][:tag_name].split(",")
    if @post.update(post_params)
      #タグ機能
      @post.save_tag(tag_list)
      #ここまで

      flash[:success] = '投稿を編集しました'
      redirect_to post_path(@post)
    else
      render :edit 
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to posts_path
  end

   #検索機能（あいまい検索）
   def search 
    @posts = Post.post_search(params[:search])
   end

  private 
  def post_params
    params.require(:post).permit(:title, :body, :post_photo)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_tag
    @tags = Tag.all
  end

  def set_ranking
    @rankings = Post.unscoped.likes_ranking
  end

  def set_history
    @histories = current_user.browsing_histories.order(id: "DESC").limit(5)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error_messages.html.erb
        <% if @post.errors.any? %>
          <div class="error-explanation">
            <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>  
        <% end %>

app/views/posts/_form_post.html.erb
    <div class="post-new-content">
      <%= form_with model: @post, local: true do |f| %>

        <%= render 'error_messages' %>
        
        <div class="post-create">
          <%= f.text_field :title, placeholder: 'タイトルを書く', class: 'post-new-field', id: 'title' %>
        </div>
        <div class="post-create">
          <%= f.text_area :body, placeholder: '本文を書く', class: 'post-new-field', rows: 10, id: 'body' %>
        </div>
        <div class="post-create">
          <%= f.file_field :post_photo %>
        </div>
        <div class="post-create tag-create">
          <span class="tag-notice">※タグを複数入力する場合はコンマを間に入れてください</span>
          <%= f.text_field :tag_name, value: @tag_list, placeholder: 'タグを入力してください', class: 'tag-field',id: 'tag_name' %>
        </div>
      
      <div class="post-new-btn-container">
        <%= f.submit '投稿する', class: 'post-new-btn'%>
      </div>
      <% end %>
    </div>

app/views/posts/_side_colums.html.erb
    <div class="post-browsing-histoies-container">
      <div class="post-history-heading">
        <h2>最近閲覧した投稿</h2>
      </div> 
      <% @histories.each do |history|  %>
        <%= link_to post_path(history.post_id), class: 'post-history-link' do %>
          <div class="browsing-histories">
            <div class="browsing-histories-image-container">
              <% if history.post.post_photo.attached? %>
                <%= image_tag history.post.post_photo, class: 'post-history-image' %>
              <% else %>
                <%= image_tag 'nothing-image.png', class: 'post-history-image' %>
              <% end %>
            </div>
            <div class="post-history-title-container">
              <p class="post-history-title"><%= history.post.title %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
     
    <div class="post-index-sub-colums-container">
      <div class="post-ranking-heading">
        <h2>人気投稿</h2>
      </div>

      <% @rankings.each.with_index(1) do |ranking, i| %>
        <%= link_to post_path(ranking), class: 'post-ranking-link' do %>
          <div class="post-ranking">
            <div class="post-ranking-image-container">
              <% if ranking.post_photo.attached? %>
                <%= image_tag ranking.post_photo, class: 'post-ranking-image' %>
              <% else %>
                <%= image_tag 'nothing-image.png', class: 'post-ranking-image' %>
              <% end %>

              <span class="ranking-number"><%= i %></span>
            </div>
            <div class="post-ranking-title-container">
              <p class="post-ranking-title"><%= ranking.title %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="post-tags-list-cotainer">
      <div class="post-tags-list-title">
        <h2>タグ一覧</h2>
      </div>

      <div class="post-tags-list">
        <% @tags.each do |tag| %>
          <%= link_to post_tag_path(tag.posts, tag), class: 'post-tags-list-link' do  %>
            <span class="post-tags-list-of-tag"><%= tag.tag_name %></span>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/posts/edit.html.erb
<div class="post-new all-wrapper">
  <div class="post-new-container all-container">
    <div class="post-new-title">
      <h3>投稿を編集する</h3>
    </div>

    <%= render 'form_post' %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="post-index all-wrapper">
  <div class="post-index-two-columns">
    <div class="post-index-container">
      <div class="post-index-title all-title">
        <h2>投稿一覧</h2>
      </div>
      <%# 検索機能 %>
      <div class="search-form">
        <%= form_with url: search_posts_path, method: :get, local: true do |f| %> <%# データベースに保存しない %>
          <%= f.text_field :search, placeholder: '投稿を検索する', class: 'seach-text-field' %>
          <%= f.submit '検索', class: 'seach-submit' %>
        <% end  %>
      </div>

      <% @posts.each do |post| %>
        <div class="post-index-link">
          <%= link_to post_path(post), class: 'link_to_allpost' do %>
            <div class="post-index-content">
              <div class="post-index-image">
                <% if post.post_photo.attached? %>
                  <%= image_tag post.post_photo, class: 'post-index-img' %>
                <% else %>
                  <%= image_tag 'nothing-image.png', class: 'post-index-img' %>
                <% end %>
              </div>

              <div class="post-index-title">
                <%= post.title %>
              </div>
            </div>
            <div class="post-index-info-container">
              <div class="tag-container">
                <% post.tags.each do |tag| %>
                  <%= link_to post_tag_path(post, tag), class: 'post-tag-index' do %>
                  <span><%= tag.tag_name %></span>
                  <% end %>
                <% end %> 
              </div>

              <div class="post-time-like-comment-container">
                <span class="post-index-info"><i class="fas fa-heart"></i><%= post.likes.count %></span>

                <span class="post-index-info"><i class="fas fa-comments"></i><%= post.comments.count %></span>
                
                <span class="post-index-info"><%= post.updated_at.strftime("%Y年%m月%d日%H時%M分") %></span>
              </div>

            </div>
              <% if @current_time < post.created_at.since(7.day
              ) %>
                <div class = "new-flag">新着</div>
              <% end %>
          <% end %>
        </div> 
      <% end %>
    </div>

    <div class="post-index-sub-colums">
     
      <%= render 'side_colums' %>
    </div>

  </div>
  <div class="pagination-container">
    <%= paginate @posts %>
  </div>
</div>

<%= javascript_pack_tag 'post/index' %>

app/views/posts/new.html.erb
<div class="post-new all-wrapper">
  <div class="post-new-container all-container">
    <div class="post-new-title">
      <h3>掲示板に投稿する</h3>
    </div>

      <%= render 'form_post' %>

  </div>
</div>

app/views/posts/search.html.erb
<div class="post-index all-wrapper">
  <div class="post-index-two-columns">
    <div class="post-index-container all-container">
      <%= link_to '一覧へ戻る >>', posts_path, class: 'post-show-back-btn' %>
        <div class="post-index-title all-title">
          <h2>検索結果<%= @posts.count %>件</h2>
        </div>

        <% @posts.each do |post| %>
            <div class="post-index-link">
              <%= link_to post_path(post) do %>
                <div class="post-index-content">
                  <div class="post-index-image">
                    <% if post.post_photo.attached? %>
                      <%= image_tag post.post_photo, class: 'post-index-img' %>
                    <% else %>
                      <%= image_tag 'nothing-image.png', class: 'post-index-img' %>
                    <% end %>
                  </div>

                  <div class="post-index-title">
                    <%= post.title %>
                  </div>
                </div>
                <div class="post-index-info-container">
                  <div class="tag-container">
                    <% post.tags.each do |tag| %>
                      <%= link_to post_tag_path(post, tag), class: 'post-tag-index' do %>
                      <span><%= tag.tag_name %></span>
                      <% end %>
                    <% end %>
                  </div>
                  
                  <div class="post-time-like-comment-container">
                    <span class="post-index-info"><i class="fas fa-heart"></i><%= post.likes.count %></span>

                    <span class="post-index-info"><i class="fas fa-comments"></i><%= post.comments.count %></span>

                    <span class="post-index-info"><%= post.created_at.strftime("%Y年%m月%d日%H時%M分") %></span>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
    </div>

    <div class="post-index-sub-colums">
      <%= render 'side_colums' %>
    </div>

  </div>
</div>      

<%= javascript_pack_tag 'post/index' %>

app/views/posts/show.html.erb
<div class="post-show all-wrapper">
  <div class="post-show-container all-container">
    <div class="posts-back-btn">
      <%= link_to '一覧へ戻る >>', posts_path, class: 'post-show-back-btn' %>
    </div>
    <div class="post-show-flex">
      <div class="post-show-time">
        <%= @post.updated_at.strftime("%Y年%m月%d日%H時%M分")%>
      </div>
      <div class="post-show-comment">
        <a class="post-comment-btn" href="#to-comment">コメントを投稿する</a>
      </div>
    </div>

      <div class="post-show-image">
          <% if @post.user.user_photo.attached? %>
            <%= image_tag @post.user.user_photo, class: 'post-show-img'%>
          <% else %>
            <%= image_tag 'no-image.png', class: 'post-show-img' %>
          <% end %>
      </div>

    <div class="post-show-flex post-show-border">
      <div class="post-show-username">
        <span>投稿者：<%= link_to @post.user.username, user_path(@post.user_id), class: 'post-user' %></span>
      </div>
      <% if @post.user.id == current_user.id %>
        <div class="post-show-edit-destroy">
          <%= link_to  '編集する',edit_post_path(@post), class: 'post-show-btn' %>
          <%= link_to  '削除する',post_path(@post), method: :delete, data: {confirm: 'この投稿を削除しますか？'}, class: 'post-show-btn' %>
        </div>
      <% end %>
    </div>

      <div class="post-tag-show-container">
        <% @post.tags.each do |tag| %>
           <%= link_to post_tag_path(@post, tag), class: 'post-tag-show' do %>
            <span><%= tag.tag_name %></span>
          <% end %>
        <% end %>
      </div>

      <div class="post-show-title">
        <h3><%= @post.title %></h3>
      </div>

      <div class="post-show-body">
        <%= simple_format(@post.body) %>
      </div>

      <div class="post-show-like">
        <%= render partial: 'likes/like', locals: { post: @post } %>
      </div>


    
      <% @comments.reverse.each do |comment|%>
        <div class="comment-all">
          <div class="comment-user-images">
            <% if comment.user.user_photo.attached? %>
              <%= image_tag comment.user.user_photo,  class: 'comment-user-img' %>
            <% else %>
              <%= image_tag 'no-image.png',  class: 'comment-user-img' %>
            <% end %>
          </div>
          <div class="comment-content">
            <p class="comment-username"><%= comment.user.username%></p>
            <p class="comment-text"><%= simple_format(comment.content ) %></p>
          </div>
          <% if  comment.user_id == current_user.id %>
            <div class="comment-delete">
              <%= link_to  '削除',post_comment_path(comment.post.id, comment.id), method: :delete, data: {confirm: 'このコメントを削除しますか？'}, class: 'comment-delete-btn' %>
            </div>
          <% end %>
         </div>
        
          <p class="comment-time"><%= comment.set_date%></p>
      <% end %>
   

      <div class="post-show-comment" id="to-comment">
        <div class="post-show-comment-title">
          <h3>コメントを投稿する</h3>
        </div>
        <%= form_with(model: [@post, @comment]) do |f| %>
          <%= f.text_area :content, class: 'comment-text-area',rows: 10, placeholder: 'コメントを書く', id: 'comment_feild' %>
          <div class="post-comment-submit">
            <%= f.submit 'コメントを投稿する', class: 'comment-submit' %>
          </div>
        <% end %>
      </div>
  </div>
</div>