config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  devise_for :users 
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do #memberによりidの識別がされるようになる（:idと同じ）
      get :followings, :followers
    end
    get :search, on: :collection #urlにidをつけない
  end
  resources :relationships, only: [:create, :destroy]

  #dm機能
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    get :search, on: :collection #urlにidをつけない
    resources :tags, only: [:show]
  end

  #通知機能
  resources :notifications, only: [:index, :destroy]
  
end

app/views/layouts/_header.html.erb
    <div id="header">
      <div class="header-container">
        <header>
          <div class="header-logo">
            <%= link_to 'Ks Essentails', root_path, class: 'header-logo-link'%>
            <% if user_signed_in? %>
              <span class="login-username"><%= current_user.username %>さんようこそ！</span>
            <% end %>
          </div>


          <div class="header-menu" id="header-menu-id">
            <ul>
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ',user_path(current_user.id), class: 'header-menu-content'%></li>
              <li><%= link_to '投稿一覧',posts_path, class: 'header-menu-content'%></li>
              <li><%= link_to 'ユーザ一覧',users_path, class: 'header-menu-content'%></li>
              <li class="notification-position"><%= link_to '通知',notifications_path, class: 'header-menu-content'%>
              <% if unchecked_notifications.any? %>
                <span class="notification-circle"><%= unchecked_notifications.count %></span>
              <% end %>
              </li>
              <li><%= link_to '新規投稿',new_post_path, class: 'header-menu-content'%></li>
              <li><%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: 'header-menu-btn'%></li>
              <% else %>
                <li><%= link_to 'ゲストログイン',users_guest_sign_in_path, method: :post, class: 'header-menu-btn'%></li>
                <li><%= link_to 'ログイン',user_session_path , class: 'header-menu-btn'%></li>
                <li><%= link_to '新規登録', new_user_registration_path, class: 'header-menu-btn'%></li>
              <% end %>
            </ul>
          </div>

          <div class="responsive-menu">
            <div class="menu-icon" id="menu-icon">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div class="responsive-menu-content" id="menu-content">
              <ul>
                <% if user_signed_in? %>
                  <li><%= link_to 'マイページ',user_path(current_user.id), class: 'header-menu-btn'%></li>
                  <li><%= link_to '投稿一覧',posts_path, class: 'header-menu-btn'%></li>
                  <li><%= link_to 'ユーザー一覧',users_path, class: 'header-menu-btn'%></li>
                  <li><%= link_to '通知',notifications_path, class: 'header-menu-btn'%></li>
                  <li><%= link_to '新規投稿',new_post_path, class: 'header-menu-btn'%></li>
                  <li><%= link_to 'ログアウト',destroy_user_session_path , class: 'header-menu-btn'%></li>
                <% else %>
                  <li><%= link_to 'ログイン',user_session_path , class: 'header-menu-btn'%></li>
                  <li><%= link_to '新規登録', new_user_registration_path, class: 'header-menu-btn'%></li>
                <% end %>
              </ul>
            </div>
          </div>

        </header>
      </div>
    </div>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
 <%= content_tag(:div, value, class: "#{key}" )%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ks Essentails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <%= render 'layouts/notice' %>
  <%= render 'layouts/header' %>

   
    <%= yield %>
     <div class="return-top">
      <span id="top-btn"><i class="fas fa-angle-up"></i></span>
    </div>

  </body>
</html>